GCC = gcc

TARGET_NAME = dkbk.exe
TARGET_OBJS = banner.o crusher.o donkey.o graphics.o hand.o hiscore.o \
	      level.o main.o particle.o player.o title.o

CFLAGS = -Wall -O3
LFLAGS = -Wl,--subsystem=windows -s -lalleg

default: all

$(TARGET_NAME): $(TARGET_OBJS) icon.res
	$(GCC) -o $@ $^ $(LFLAGS)

%.o: %.c
	$(GCC) $(CFLAGS) -o $@ -c $<

%.res: %.rc
	windres -O coff -o $@ -i $<

all: $(TARGET_NAME)
