GCC = gcc

TARGET_NAME = dkbk
TARGET_OBJS = banner.o crusher.o donkey.o graphics.o hand.o hiscore.o \
	      level.o main.o particle.o player.o title.o

CFLAGS = -Wall -m486 -O3 -ffast-math
LFLAGS = -s `allegro-config --libs`

default: all

$(TARGET_NAME): $(TARGET_OBJS)
	$(GCC) -o $@ $^ $(LFLAGS)

%.o: %.c
	$(GCC) $(CFLAGS) -o $@ -c $<

all: $(TARGET_NAME)
